use_frameworks!


# 引入flutter模块
flutter_application_path = '../my_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'AppModuleA_Example' do
  pod 'AppModuleA', :path => '../'
  
  # 安装Flutter模块
  install_all_flutter_pods(flutter_application_path)
  
  target 'AppModuleA_Tests' do
    inherit! :search_paths

    
  end
end
